import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';
import {ApiError,validateEnvelope,validateState} from './validation.mjs';import {REPO,BRANCH,STATE_PATH} from './github.mjs';
export function validKnownHosts(text){const lines=text.trim().split('\n');return lines.length===3&&lines.every(line=>/^github\.com,\[ssh\.github\.com\]:443 (ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp256) [A-Za-z0-9+/=]+$/.test(line))&&new Set(lines.map(line=>line.split(' ')[1])).size===3;}
const exec=promisify(execFile);const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export class GitStore {
 constructor({key=process.env.GITHUB_DEPLOY_KEY_B64,runImpl,writeImpl=writeFile,workdir}={}){this.key=key;this.runImpl=runImpl;this.write=writeImpl;this.workdir=workdir;this.queue=Promise.resolve();}
 async lock(fn){const prior=this.queue;let release;this.queue=new Promise(r=>{release=r;});await prior;try{return await fn();}finally{release();}}
 async initialize(){if(this.runImpl)return;if(this.ready)return;if(!this.key)throw new ApiError(503,'保存サーバーの設定が未完了です');
  try{const root=await mkdtemp(join(tmpdir(),'q3-progress-'));const privateKey=join(root,'deploy_key'),knownHosts=join(root,'known_hosts');await writeFile(privateKey,Buffer.from(this.key,'base64'),{mode:0o600});const hostKeys=await readFile(new URL('./github_known_hosts',import.meta.url),'utf8');if(!validKnownHosts(hostKeys))throw new ApiError(502,'GitHub接続先の公開鍵設定を確認できません');await writeFile(knownHosts,hostKeys,{mode:0o600});this.gitEnv={...process.env,GIT_TERMINAL_PROMPT:'0',GIT_SSH_COMMAND:`ssh -p 443 -o Hostname=ssh.github.com -o ConnectTimeout=15 -i ${privateKey} -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=${knownHosts}`,GIT_AUTHOR_NAME:'3Q progress dashboard',GIT_AUTHOR_EMAIL:'q3-dashboard@users.noreply.github.com',GIT_COMMITTER_NAME:'3Q progress dashboard',GIT_COMMITTER_EMAIL:'q3-dashboard@users.noreply.github.com'};delete this.gitEnv.GITHUB_DEPLOY_KEY_B64;delete this.gitEnv.GITHUB_TOKEN;this.workdir=join(root,'repository');await mkdir(this.workdir);await this.run(['clone','--single-branch','--branch',BRANCH,`git@github.com:${REPO}.git`,'.']);this.ready=true;this.key=undefined;
  }catch(e){if(e instanceof ApiError)throw e;throw new ApiError(502,'GitHubの保存先に接続できません');}
 }
 async run(args){if(this.runImpl)return this.runImpl(args);const result=await exec('git',args,{cwd:this.workdir,env:this.gitEnv,timeout:45000,maxBuffer:8*1024*1024});return result.stdout.trim();}
 async sync(){await this.initialize();try{await this.run(['fetch','origin',BRANCH]);await this.run(['reset','--hard',`origin/${BRANCH}`]);}catch{throw new ApiError(502,'最新データを取得できません。下書きを保持してください');}}
 async read(){try{const state=JSON.parse(await this.run(['show',`HEAD:${STATE_PATH}`]));validateState(state);const revision=await this.run(['rev-parse',`HEAD:${STATE_PATH}`]);return {state,revision};}catch{throw new ApiError(502,'保存済みデータを確認できません。Git履歴を確認してください');}}
 async get(){return this.lock(async()=>{await this.sync();return this.read();});}
 async save(body){validateEnvelope(body);return this.lock(async()=>{await this.sync();const current=await this.read(),fingerprint=hash(body);let log;try{log=await this.run(['log','--format=%H%n%B%x00','--',STATE_PATH]);}catch{throw new ApiError(502,'保存履歴を確認できません');}
  for(const entry of log.split('\0')){const match=entry.match(/\nQ3-Request: ([0-9a-f-]+) ([0-9a-f]{64})(?:\n|$)/i);if(match?.[1]===body.requestId){if(match[2]!==fingerprint)throw new ApiError(409,'この保存IDは別の内容です。新しい保存として実行してください');const commit=entry.trim().split('\n')[0];return {...current,commitUrl:`https://github.com/${REPO}/commit/${commit}`,updatedAt:current.state.updatedAt,deduplicated:true};}}
  if(current.revision!==body.revision)throw new ApiError(409,'他の人が更新しました。下書きを残して最新を読み込んでください');validateState(body.state,current.state.baseline);const state=structuredClone(body.state);state.updatedAt=new Date().toISOString();
  try{await this.write(join(this.workdir,STATE_PATH),JSON.stringify(state,null,2)+'\n');await this.run(['add','--',STATE_PATH]);await this.run(['commit','-m',`週次の進捗を共有するため更新（${body.editor.replace(/[\r\n]/g,' ')}）\n\nQ3-Request: ${body.requestId} ${fingerprint}\n`]);}catch{throw new ApiError(502,'保存準備が完了しませんでした。下書きを保持してください');}
  const commit=await this.run(['rev-parse','HEAD']);try{await this.run(['push','origin',`HEAD:refs/heads/${BRANCH}`]);}catch{ // Resolve ambiguous transport failure without losing a committed retry.
   try{await this.run(['fetch','origin',BRANCH]);const remoteLog=await this.run(['log',`origin/${BRANCH}`,'--format=%B','--',STATE_PATH]);if(!remoteLog.includes(`Q3-Request: ${body.requestId} ${fingerprint}`))throw Error();}catch{throw new ApiError(409,'保存を確認できませんでした。別の更新や接続を確認し、下書きを保持してください');}
  }
  await this.sync();const verified=await this.read();if(!isDeepStrictEqual(verified.state,state)){ // A later writer may advance HEAD after our confirmed commit; verify the precise commit.
   try{const atCommit=JSON.parse(await this.run(['show',`${commit}:${STATE_PATH}`]));if(!isDeepStrictEqual(atCommit,state))throw Error();}catch{throw new ApiError(502,'保存後の確認が完了しませんでした。同じ保存内容で再試行してください');}
  }return {...verified,commitUrl:`https://github.com/${REPO}/commit/${commit}`,updatedAt:verified.state.updatedAt};
 });}
}
