import {createWeek} from '../public/model.js';
import test from 'node:test';import assert from 'node:assert/strict';import {GitStore} from './git-store.mjs';
const sha='a'.repeat(40),state={schemaVersion:1,updatedAt:null,baseline:{septemberRevenue:554427123,septemberCvr:null,q2Cvr:null,people:[],articles:[],sources:[],notes:[]},monthlyRevenue:[{month:'2026-10',actual:null,asOf:null},{month:'2026-11',actual:null,asOf:null},{month:'2026-12',actual:null,asOf:null}],articles:[],initiatives:[],weeks:[createWeek('2026-10-12')]};
const body=()=>({state:structuredClone(state),revision:sha,requestId:'550e8400-e29b-41d4-a716-446655440000',editor:'臼倉'});
function mock(){let text=JSON.stringify(state),revision=sha,log='',commands=[];const run=async(args)=>{commands.push(args);if(args[0]==='show')return text;if(args[0]==='rev-parse')return args[1].includes(':')?revision:'c'.repeat(40);if(args[0]==='log')return log;if(args[0]==='commit'){log=args[2];revision='b'.repeat(40);}return '';};const store=new GitStore({runImpl:run,writeImpl:async(_,value)=>{text=value;},workdir:'/tmp/q3-test'});return {store,commands,setCurrent(s){text=JSON.stringify(s);revision='d'.repeat(40);}};}
test('git writes only fixed file and pushes fixed branch',async()=>{const m=mock();const r=await m.store.save(body());assert.equal(r.revision,'b'.repeat(40));assert.ok(m.commands.some(a=>a.join(' ')==='add -- data/state.json'));assert.ok(m.commands.some(a=>a.join(' ')==='push origin HEAD:refs/heads/codex/3q-dashboard'));});
test('SSH revision conflict writes nothing',async()=>{const m=mock(),b=body();b.revision='e'.repeat(40);await assert.rejects(()=>m.store.save(b),e=>e.status===409);assert.ok(!m.commands.some(a=>a[0]==='add'));});
test('SSH history dedup after new state does not overwrite',async()=>{const m=mock(),b=body();await m.store.save(b);const newer=structuredClone(state);newer.monthlyRevenue[0].actual=12;m.setCurrent(newer);assert.equal((await m.store.save(b)).state.monthlyRevenue[0].actual,12);assert.equal(m.commands.filter(a=>a[0]==='push').length,1);});
test('reused requestId with different content cannot overwrite',async()=>{const m=mock(),b=body();await m.store.save(b);b.state.monthlyRevenue[0].actual=123;await assert.rejects(()=>m.store.save(b),e=>e.status===409);assert.equal(m.commands.filter(a=>a[0]==='push').length,1);});
test('failed push cannot report saved or expose git stderr',async()=>{const m=mock(),original=m.store.runImpl;m.store.runImpl=async args=>{if(args[0]==='push')throw new Error('secret from ssh stderr');if(args[0]==='log'&&args[1]?.startsWith('origin/'))return '';return original(args);};await assert.rejects(()=>m.store.save(body()),e=>e.status===409&&!e.message.includes('secret'));});
test('pinned GitHub host keys cover HTTPS-port SSH without runtime API dependency',async()=>{const {validKnownHosts}=await import('./git-store.mjs');const {readFile}=await import('node:fs/promises');const keys=await readFile(new URL('./github_known_hosts',import.meta.url),'utf8');assert.equal(validKnownHosts(keys),true);assert.equal(validKnownHosts(keys.replace('github.com','evil.example')),false);assert.equal(validKnownHosts(''),false);});
