import test from 'node:test';import assert from 'node:assert/strict';
import {GitHubStore} from './github.mjs';
const base={schemaVersion:1,updatedAt:null,baseline:{septemberRevenue:554427123,septemberCvr:null,q2Cvr:null,people:[],articles:[],sources:[],notes:[]},monthlyRevenue:[{month:'2026-10',actual:null,asOf:null},{month:'2026-11',actual:null,asOf:null},{month:'2026-12',actual:null,asOf:null}],articles:[],initiatives:[],weeks:[]};
const request=()=>({state:structuredClone(base),revision:'a'.repeat(40),requestId:'550e8400-e29b-41d4-a716-446655440000',editor:'臼倉'});
const reply=(json,status=200)=>new Response(JSON.stringify(json),{status});
function mockStore(){let state=structuredClone(base),sha='a'.repeat(40),commits=[],puts=0;const fetchImpl=async(url,options={})=>{assert.ok(url.startsWith('https://api.github.com/repos/usukura-P/conversion-design-q3-2026/'));assert.equal(options.headers.Authorization,'Bearer hidden');if(url.includes('/commits?'))return reply(commits);if(options.method==='PUT'){puts++;const body=JSON.parse(options.body);if(body.sha!==sha)return reply({},409);state=JSON.parse(Buffer.from(body.content,'base64'));sha='b'.repeat(40);commits.unshift({sha:'c'.repeat(40),commit:{message:body.message},html_url:'https://github.com/usukura-P/conversion-design-q3-2026/commit/'+'c'.repeat(40)});return reply({content:{sha},commit:{sha:'c'.repeat(40),html_url:commits[0].html_url}},201);}return reply({sha,encoding:'base64',content:Buffer.from(JSON.stringify(state)).toString('base64')});};return {store:new GitHubStore({token:'hidden',fetchImpl}),puts:()=>puts,setState:s=>{state=s;sha='d'.repeat(40);}};}
test('update reads back committed data and never permits caller repo override',async()=>{const m=mockStore();const r=await m.store.save(request());assert.equal(r.revision,'b'.repeat(40));assert.equal(m.puts(),1);assert.ok(r.updatedAt);});
test('stale SHA returns 409 before write',async()=>{const m=mockStore(),r=request();r.revision='e'.repeat(40);await assert.rejects(()=>m.store.save(r),e=>e.status===409);assert.equal(m.puts(),0);});
test('persistent replay after another save returns current state without overwriting',async()=>{const m=mockStore(),r=request();await m.store.save(r);const latest=structuredClone(base);latest.monthlyRevenue[0].actual=999;m.setState(latest);const result=await m.store.save(r);assert.equal(result.state.monthlyRevenue[0].actual,999);assert.equal(result.revision,'d'.repeat(40));assert.equal(m.puts(),1);});
test('reuse requestId with changed payload rejects',async()=>{const m=mockStore(),r=request();await m.store.save(r);r.state.monthlyRevenue[0].actual=42;await assert.rejects(()=>m.store.save(r),e=>e.status===409);assert.equal(m.puts(),1);});
test('GitHub failure does not expose body or token',async()=>{const s=new GitHubStore({token:'secret',fetchImpl:async()=>reply({message:'secret internal'},403)});await assert.rejects(()=>s.get(),e=>e.status===502&&!e.message.includes('secret'));});
