import {createServer} from 'node:http';import {pathToFileURL} from 'node:url';import {ApiError} from './validation.mjs';import {GitStore} from './git-store.mjs';import {GitHubStore} from './github.mjs';
const MAX_BODY=512*1024;
const allowed=origin=>origin==='https://usukura-p.github.io'||/^http:\/\/(localhost|127\.0\.0\.1)(:\d{1,5})?$/.test(origin);
async function readBody(req){if(Number(req.headers['content-length'])>MAX_BODY){req.resume();throw new ApiError(413,'保存内容が512KBを超えています');}return new Promise((resolve,reject)=>{let total=0,parts=[],rejected=false;req.on('data',chunk=>{if(rejected)return;total+=chunk.length;if(total>MAX_BODY){rejected=true;parts=[];reject(new ApiError(413,'保存内容が512KBを超えています'));return;}parts.push(chunk);});req.on('end',()=>{if(!rejected){try{resolve(JSON.parse(Buffer.concat(parts).toString('utf8')));}catch{reject(new ApiError(400,'JSON形式が不正です'));}}});req.on('error',()=>reject(new ApiError(400,'送信が中断されました')));});}
export function createApiServer(store=process.env.GITHUB_DEPLOY_KEY_B64?new GitStore():new GitHubStore()){
 return createServer(async(req,res)=>{res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const origin=req.headers.origin;
 const send=(status,value)=>{res.statusCode=status;res.end(JSON.stringify(value));};
 try{if(origin&&!allowed(origin))throw new ApiError(403,'このページからのアクセスは許可されていません');if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');}if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');send(204,{});return;}const url=new URL(req.url,'http://server');if(url.search)throw new ApiError(400,'URLへの追加パラメータは指定できません');if(req.method==='GET'&&url.pathname==='/health'){send(200,{ok:true});return;}if(url.pathname!=='/api/state')throw new ApiError(404,'ページが見つかりません');if(req.method==='GET'){send(200,await store.get());return;}if(req.method==='POST'){if(!/^application\/json(?:\s*;|$)/i.test(req.headers['content-type']||''))throw new ApiError(415,'Content-Typeはapplication/jsonを指定してください');send(200,await store.save(await readBody(req)));return;}throw new ApiError(405,'この操作は利用できません');}catch(e){send(e instanceof ApiError?e.status:500,{error:e instanceof ApiError?e.message:'保存処理でエラーが発生しました。下書きを保持してください'});}
 });
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const server=createApiServer();server.listen(Number(process.env.PORT)||8080,'0.0.0.0',()=>console.log('3Q progress API listening'));server.headersTimeout=10000;server.requestTimeout=60000;}
