import {isDeepStrictEqual} from 'node:util';
export const PEOPLE=['usukura','kantake','aoki','nakagawa'];
export class ApiError extends Error {constructor(status,message){super(message);this.status=status;}}
const fail=(path)=>{throw new ApiError(400,`入力が不正です: ${path}`);};
const keys=(value,allowed,path)=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)fail(path);for(const key of Object.keys(value))if(!allowed.includes(key))fail(`${path}.${key}`);for(const key of allowed)if(!Object.hasOwn(value,key))fail(`${path}.${key}`);};
const str=(v,p,max=8000)=>{if(typeof v!=='string'||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]|<\/?[a-z!][^>]*>/i.test(v))fail(p);};
const id=(v,p)=>{str(v,p,120);if(!/^[a-zA-Z0-9_-]+$/.test(v))fail(p);};
const num=(v,p,nullable=true,max=1e12)=>{if(v===null&&nullable)return;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)fail(p);};
const count=(v,p,nullable=false)=>{num(v,p,nullable);if(v!==null&&!Number.isSafeInteger(v))fail(p);};
const one=(v,vs,p)=>{if(!vs.includes(v))fail(p);};
export const jstDate=(now=new Date())=>new Date(now.getTime()+9*3600000).toISOString().slice(0,10);
const date=(v,p,nullable=true)=>{if(v===null&&nullable)return;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))fail(p);const d=new Date(`${v}T00:00:00Z`);if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v)fail(p);};
const iso=(v,p)=>{if(v===null)return;if(typeof v!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString()!==v.replace(/Z$/,v.includes('.')?'Z':'.000Z'))fail(p);};
const array=(v,p,max=1000)=>{if(!Array.isArray(v)||v.length>max)fail(p);};
const unique=(v,k,p)=>{if(new Set(v.map(x=>x[k])).size!==v.length)fail(`${p}.重複`);};
const owner=(v,p)=>one(v,PEOPLE,p);
const cvr=(v,p)=>num(v,p,true,100);
const personMap=(v,p,fields,check)=>{keys(v,PEOPLE,p);for(const person of PEOPLE){keys(v[person],fields,`${p}.${person}`);check(v[person],`${p}.${person}`);}};
const url=(v,p)=>{str(v,p,2000);if(!v)return;try{const u=new URL(v);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)fail(p);}catch{fail(p);}};
export function validateState(s,baseline){
 keys(s,['schemaVersion','updatedAt','baseline','monthlyRevenue','articles','initiatives','weeks'],'state');if(s.schemaVersion!==1)fail('schemaVersion');iso(s.updatedAt,'updatedAt');
 keys(s.baseline,['septemberRevenue','septemberCvr','q2Cvr','people','articles','sources','notes'],'baseline');num(s.baseline.septemberRevenue,'baseline.septemberRevenue',false);cvr(s.baseline.septemberCvr,'baseline.septemberCvr');cvr(s.baseline.q2Cvr,'baseline.q2Cvr');
 array(s.baseline.people,'baseline.people',4);unique(s.baseline.people,'id','baseline.people');for(const p of s.baseline.people){keys(p,['id','name','septemberCvr','q2Cvr'],'baseline.people');owner(p.id,'baseline.people.id');str(p.name,'baseline.people.name',80);cvr(p.septemberCvr,'baseline.people.septemberCvr');cvr(p.q2Cvr,'baseline.people.q2Cvr');}
 array(s.baseline.articles,'baseline.articles');unique(s.baseline.articles,'id','baseline.articles');for(const a of s.baseline.articles){keys(a,['id','title','owner','releaseDate','metaCv','metaClicks','cvr','excluded'],'baseline.article');id(a.id,'baseline.article.id');str(a.title,'baseline.article.title',500);one(a.owner,[...PEOPLE,'ai'],'baseline.article.owner');date(a.releaseDate,'baseline.article.releaseDate',false);count(a.metaCv,'baseline.article.metaCv',true);count(a.metaClicks,'baseline.article.metaClicks',true);cvr(a.cvr,'baseline.article.cvr');if(typeof a.excluded!=='boolean')fail('baseline.article.excluded');}
 array(s.baseline.sources,'baseline.sources',30);for(const source of s.baseline.sources){keys(source,['label','url','asOf'],'baseline.source');str(source.label,'baseline.source.label',2000);url(source.url,'baseline.source.url');date(source.asOf,'baseline.source.asOf');}array(s.baseline.notes,'baseline.notes',100);for(const note of s.baseline.notes)str(note,'baseline.notes');
 if(baseline&&!isDeepStrictEqual(s.baseline,baseline))throw new ApiError(400,'9月・2Qの基準値は変更できません');
 array(s.monthlyRevenue,'monthlyRevenue',3);if(s.monthlyRevenue.length!==3)fail('monthlyRevenue');unique(s.monthlyRevenue,'month','monthlyRevenue');for(const r of s.monthlyRevenue){keys(r,['month','actual','asOf'],'monthlyRevenue');one(r.month,['2026-10','2026-11','2026-12'],'month');num(r.actual,'actual');date(r.asOf,'asOf');}
 array(s.articles,'articles');unique(s.articles,'id','articles');for(const a of s.articles){keys(a,['id','title','owner','releaseDate','metaCv','metaClicks','observedThrough','initiativeId'],'article');id(a.id,'article.id');str(a.title,'article.title',500);owner(a.owner,'article.owner');date(a.releaseDate,'article.releaseDate',false);date(a.observedThrough,'article.observedThrough');if(a.observedThrough&&(a.observedThrough<a.releaseDate||a.observedThrough>jstDate()))fail('article.observedThrough');count(a.metaCv,'article.metaCv',true);count(a.metaClicks,'article.metaClicks',true);if(a.metaCv!==null&&a.metaClicks!==null&&a.metaCv>a.metaClicks)fail('article.metaCv');if(a.initiativeId!==null)id(a.initiativeId,'article.initiativeId');}
 array(s.initiatives,'initiatives');unique(s.initiatives,'id','initiatives');for(const i of s.initiatives){keys(i,['id','title','owner','stage','meetingDate','dispatchDate','deadline','evidence','background','craft','feedback','learning','next','url'],'initiative');id(i.id,'initiative.id');str(i.title,'initiative.title',500);owner(i.owner,'initiative.owner');one(i.stage,['idea','meeting','agreed','production','released','dispatched','reviewed'],'stage');for(const k of ['meetingDate','dispatchDate','deadline'])date(i[k],k);for(const k of ['evidence','background','craft','feedback','learning','next'])str(i[k],k);url(i.url,'initiative.url');}
 for(const a of s.articles)if(a.initiativeId!==null&&!s.initiatives.some(i=>i.id===a.initiativeId))fail('article.initiativeId');
 array(s.weeks,'weeks',40);unique(s.weeks,'id','weeks');for(const w of s.weeks){keys(w,['id','releaseStart','releaseEnd','team','members','qualitative','metrics'],'week');date(w.id,'week.id',false);const monday=new Date(`${w.id}T00:00:00Z`);if(monday.getUTCDay()!==1)fail('week.id 月曜日');for(const [k,offset] of [['releaseStart',7],['releaseEnd',1]]){date(w[k],k,false);if(w[k]!==new Date(monday.getTime()-offset*86400000).toISOString().slice(0,10))fail(k);}
 keys(w.team,['status','change','issues','priorities','requests'],'team');for(const [k,v]of Object.entries(w.team))str(v,`team.${k}`);personMap(w.members,'members',['reflection','feedback','action'],(m,p)=>{for(const [k,v]of Object.entries(m))str(v,`${p}.${k}`);});array(w.qualitative,'qualitative',30);unique(w.qualitative,'id','qualitative');for(const q of w.qualitative){keys(q,['id','status','evidence','next'],'qualitative');id(q.id,'qualitative.id');one(q.status,['not_started','in_progress','achieved'],'qualitative.status');str(q.evidence,'qualitative.evidence');str(q.next,'qualitative.next');}
 const m=w.metrics;keys(m,['asOf','teamCvr','previousWeekCvr','eligibleArticles','unmeasurableArticles','dispatched','people'],'metrics');iso(m.asOf,'metrics.asOf');cvr(m.teamCvr,'metrics.teamCvr');cvr(m.previousWeekCvr,'metrics.previousWeekCvr');for(const k of ['eligibleArticles','unmeasurableArticles','dispatched'])count(m[k],`metrics.${k}`);personMap(m.people,'metrics.people',['cvr','proposals'],(p,path)=>{cvr(p.cvr,`${path}.cvr`);count(p.proposals,`${path}.proposals`);});
 }
}
export function validateEnvelope(body){keys(body,['state','revision','requestId','editor'],'request');if(typeof body.revision!=='string'||!/^[a-f0-9]{40,64}$/.test(body.revision))fail('revision');if(typeof body.requestId!=='string'||!/^\w{8}-\w{4}-[1-8]\w{3}-[89ab]\w{3}-\w{12}$/i.test(body.requestId)||!/^[0-9a-f-]+$/i.test(body.requestId))fail('requestId');str(body.editor,'editor',80);if(!body.editor.trim())fail('editor');validateState(body.state);}
